# Site Settings
title:               Michael Choi 
tagline:             
description:
baseurl:            "/about"
url:                #"https://lenpaul.github.io"
github:
  url:               #"https://lenpaul.github.io/Lagrange"
author:
  name:              "Michael Choi"
  email:             "michael.choi@yale-nus.edu.sg"
  twitter:           "michaelchchoi"
  #instagram:         #"paululele"
  github:            "mchchoi"
#  facebook:          #"Le.Paul.94"
#  linkedin:          #"lenpaul"
navigation:
- title: About
  url: /about
- title: Research
  url: /research
- title: Teaching
  url: /teaching
- title: Service
  url: /service
#- title: Minicourse on Markov chain mixing time
#  url: /mcmt
#- title: Writing
#  url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
theme:               jekyll-theme-primer
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
